// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NotificationSystem.Models;
using System;
using System.Collections.Generic;

namespace NotificationSystem.Models.Configurations
{
    public partial class FoodOrderConfiguration : IEntityTypeConfiguration<FoodOrder>
    {
        public void Configure(EntityTypeBuilder<FoodOrder> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__FoodOrde__3214EC078515438B");

            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.OrderedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Pending");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FoodOrder> entity);
    }
}
