// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotificationSystem.Models;

public partial class FoodOrder
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string ItemName { get; set; }

    public int Quantity { get; set; }

    public DateTime OrderedAt { get; set; }

    public string Status { get; set; }
}