// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using NotificationSystem.Models.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace NotificationSystem.Models;

public partial class OfficeCanteenDBContext : DbContext
{
    public OfficeCanteenDBContext(DbContextOptions<OfficeCanteenDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FoodOrder> FoodOrders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.FoodOrderConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
